config/routes.rb
        get '/:id/grade/edit' => 'degrees/grade#edit', as: :degrees_grade_edit
        post '/:id/grade' => 'degrees/grade#update', as: :degrees_create_grade

        get '/:id/year' => 'degrees/year#new', as: :degrees_year
        get '/:id/year/edit' => 'degrees/year#edit', as: :degrees_year_edit
        post '/:id/year' => 'degrees/year#update', as: :degrees_create_year

        get '/review' => 'degrees/review#show', as: :degrees_review
        patch '/review' => 'degrees/review#complete', as: :degrees_complete

        get '/edit/:id' => 'degrees/base#edit', as: :degrees_edit
        post '/edit/:id' => 'degrees/base#update'

        get '/delete/:id' => 'degrees/destroy#confirm_destroy', as: :confirm_degrees_destroy
        delete '/delete/:id' => 'degrees/destroy#destroy'
      end

      scope '/courses' do
        get '/' => 'course_choices#index', as: :course_choices_index

        get '/choose' => 'course_choices#have_you_chosen', as: :course_choices_choose
        post '/choose' => 'course_choices#make_choice'

        get '/delete/:id' => 'course_choices#confirm_destroy', as: :confirm_destroy_course_choice
        delete '/delete/:id' => 'course_choices#destroy'

        get '/provider' => 'course_choices#options_for_provider', as: :course_choices_provider
        post '/provider' => 'course_choices#pick_provider'

        get '/apply-on-ucas' => 'course_choices#ucas', as: :course_choices_on_ucas

        get '/provider/:provider_code/courses' => 'course_choices#options_for_course', as: :course_choices_course
        post '/provider/:provider_code/courses' => 'course_choices#pick_course'

        get '/provider/:provider_code/courses/:course_code' => 'course_choices#options_for_site', as: :course_choices_site
        post '/provider/:provider_code/courses/:course_code' => 'course_choices#pick_site'

        get '/review' => 'course_choices#review', as: :course_choices_review
        patch '/review' => 'course_choices#complete', as: :course_choices_complete
      end

      scope '/choice/:id' do
        get '/offer' => 'decisions#offer', as: :offer
        post '/offer/respond' => 'decisions#respond_to_offer', as: :respond_to_offer

        get '/offer/decline' => 'decisions#decline', as: :decline_offer
        post '/offer/decline' => 'decisions#confirm_decline'

        get '/offer/accept' => 'decisions#accept', as: :accept_offer
        post '/offer/accept' => 'decisions#confirm_accept'

        get '/withdraw' => 'decisions#withdraw', as: :withdraw
        post '/withdraw' => 'decisions#confirm_withdraw'
      end

      scope '/other-qualifications' do
        get '/' => 'other_qualifications/base#new', as: :new_other_qualification
        post '/' => 'other_qualifications/base#create', as: :create_other_qualification

        get '/review' => 'other_qualifications/review#show', as: :review_other_qualifications
        patch '/review' => 'other_qualifications/review#complete', as: :complete_other_qualifications

        get '/edit/:id' => 'other_qualifications/base#edit', as: :edit_other_qualification
        post '/edit/:id' => 'other_qualifications/base#update'

        get '/delete/:id' => 'other_qualifications/destroy#confirm_destroy', as: :confirm_destroy_other_qualification
        delete '/delete/:id' => 'other_qualifications/destroy#destroy'
      end

      scope '/referees' do
        get '/' => 'referees#index', as: :referees
        get '/new' => 'referees#new', as: :new_referee
        post '/' => 'referees#create'

        get '/review' => 'referees#review', as: :review_referees
        patch '/review' => 'referees#complete', as: :complete_referees

        get '/edit/:id' => 'referees#edit', as: :edit_referee
        patch '/update/:id' => 'referees#update', as: :update_referee

        get '/delete/:id' => 'referees#confirm_destroy', as: :confirm_destroy_referee
        delete '/delete/:id' => 'referees#destroy', as: :destroy_referee
      end

      scope '/new-referee' do
        get '/' => 'additional_referees#show', as: :additional_referee
        get '/new' => 'additional_referees#new', as: :new_additional_referee
        post '/new' => 'additional_referees#create'

        get '/:application_reference_id/edit' => 'additional_referees#edit', as: :edit_additional_referee
        patch '/:application_reference_id/edit' => 'additional_referees#update'

        get '/confirm' => 'additional_referees#confirm', as: :confirm_additional_referees
        post '/confirm' => 'additional_referees#request_references'
      end
    end
  end

  namespace :referee_interface, path: '/reference' do
    get '/' => 'reference#feedback', as: :reference_feedback

    get '/confirmation' => 'reference#confirmation', as: :confirmation
    patch '/confirmation' => 'reference#submit_feedback', as: :submit_feedback

    patch '/questionnaire' => 'reference#submit_questionnaire', as: :submit_questionnaire
    get '/finish' => 'reference#finish', as: :finish

    get '/refuse-feedback' => 'reference#refuse_feedback', as: :refuse_feedback
    patch '/refuse-feedback' => 'reference#confirm_feedback_refusal'
  end

  namespace :vendor_api, path: 'api/v1' do
    get '/applications' => 'applications#index'
    get '/applications/:application_id' => 'applications#show'

    post '/applications/:application_id/offer' => 'decisions#make_offer'
    post '/applications/:application_id/confirm-conditions-met' => 'decisions#confirm_conditions_met'
    post '/applications/:application_id/conditions-not-met' => 'decisions#conditions_not_met'
    post '/applications/:application_id/reject' => 'decisions#reject'
    post '/applications/:application_id/confirm-enrolment' => 'decisions#confirm_enrolment'

    post '/test-data/regenerate' => 'test_data#regenerate'
    post '/experimental/test-data/generate' => 'test_data#generate'
    post '/experimental/test-data/clear' => 'test_data#clear!'

    get '/ping', to: 'ping#ping'
  end

  namespace :provider_interface, path: '/provider' do
    get '/' => 'start_page#show'

    get '/accessibility', to: 'content#accessibility'
    get '/privacy-policy', to: 'content#privacy_policy', as: :privacy_policy
    get '/cookies', to: 'content#cookies_provider', as: :cookies
    get '/terms-of-use', to: 'content#terms_provider', as: :terms

    get '/data-sharing-agreements/new', to: 'provider_agreements#new_data_sharing_agreement', as: :new_data_sharing_agreement
    post '/data-sharing-agreements', to: 'provider_agreements#create_data_sharing_agreement', as: :create_data_sharing_agreement
    get '/data-sharing-agreements/:id', to: 'provider_agreements#show_data_sharing_agreement', as: :show_data_sharing_agreement

    get '/applications' => 'application_choices#index'
    get '/applications/:application_choice_id' => 'application_choices#show', as: :application_choice
    get '/applications/:application_choice_id/respond' => 'decisions#respond', as: :application_choice_respond
    post '/applications/:application_choice_id/respond' => 'decisions#submit_response', as: :application_choice_submit_response
    get '/applications/:application_choice_id/offer' => 'decisions#new_offer', as: :application_choice_new_offer
    get '/applications/:application_choice_id/reject' => 'decisions#new_reject', as: :application_choice_new_reject
    post '/applications/:application_choice_id/reject/confirm' => 'decisions#confirm_reject', as: :application_choice_confirm_reject
    post '/applications/:application_choice_id/reject' => 'decisions#create_reject', as: :application_choice_create_reject
    post '/applications/:application_choice_id/offer/confirm' => 'decisions#confirm_offer', as: :application_choice_confirm_offer
    post '/applications/:application_choice_id/offer' => 'decisions#create_offer', as: :application_choice_create_offer
    get '/applications/:application_choice_id/conditions' => 'conditions#edit', as: :application_choice_edit_conditions
    patch '/applications/:application_choice_id/conditions/confirm' => 'conditions#confirm_update', as: :application_choice_confirm_update_conditions
    patch '/applications/:application_choice_id/conditions' => 'conditions#update', as: :application_choice_update_conditions
    get '/applications/:application_choice_id/edit_response' => 'decisions#new_edit_response', as: :application_choice_new_edit_response
    post '/applications/:application_choice_id/edit_response' => 'decisions#edit_response', as: :application_choice_edit_response
    get '/applications/:application_choice_id/offer/new_withdraw' => 'decisions#new_withdraw_offer', as: :application_choice_new_withdraw_offer
    post '/applications/:application_choice_id/offer/confirm_withdraw' => 'decisions#confirm_withdraw_offer', as: :application_choice_confirm_withdraw_offer
    post '/applications/:application_choice_id/offer/withdraw' => 'decisions#withdraw_offer', as: :application_choice_withdraw_offer

    post '/candidates/:candidate_id/impersonate' => 'candidates#impersonate', as: :impersonate_candidate

    get '/sign-in' => 'sessions#new'
    get '/sign-out' => 'sessions#destroy'
  end

  get '/auth/dfe/callback' => 'dfe_sign_in#callback'
  post '/auth/developer/callback' => 'dfe_sign_in#bypass_callback'

  namespace :integrations, path: '/integrations' do
    post '/notify/callback' => 'notify#callback'
    get '/feature-flags' => 'feature_flags#index'
  end

  namespace :support_interface, path: '/support' do
    get '/' => redirect('/support/candidates')

    get '/provider-flow', to: 'docs#provider_flow', as: :provider_flow
    get '/candidate-flow', to: 'docs#candidate_flow', as: :candidate_flow

    get '/applications' => 'application_forms#index'
    get '/applications/:application_form_id' => 'application_forms#show', as: :application_form
    get '/applications/:application_form_id/audit' => 'application_forms#audit', as: :application_form_audit

app/models/candidate_interface/becoming_a_teacher_form.rb
module CandidateInterface
  class BecomingATeacherForm
    include ActiveModel::Model

    attr_accessor :becoming_a_teacher

    validates :becoming_a_teacher,
              word_count: { maximum: 600 },
              presence: true

    def self.build_from_application(application_form)
      new(
        becoming_a_teacher: application_form.becoming_a_teacher,
      )
    end

    def save(application_form)
      return false unless valid?

      application_form.update(
        becoming_a_teacher: becoming_a_teacher,
      )
    end
  end
end

app/models/candidate_interface/contact_details_form.rb
module CandidateInterface
  class ContactDetailsForm
    include ActiveModel::Model

    attr_accessor :phone_number, :address_line1, :address_line2, :address_line3,
                  :address_line4, :postcode

    validates :address_line1, :address_line3, :postcode, presence: true, on: :address

    validates :address_line1, :address_line2, :address_line3, :address_line4,
              length: { maximum: 50 }, on: :address

    validates :phone_number, length: { maximum: 50 }, phone_number: true, on: :base

    validates :postcode, postcode: true, on: :address

    def self.build_from_application(application_form)
      new(
        phone_number: application_form.phone_number,
        address_line1: application_form.address_line1,
        address_line2: application_form.address_line2,
        address_line3: application_form.address_line3,
        address_line4: application_form.address_line4,
        postcode: application_form.postcode,
      )
    end

    def save_base(application_form)
      return false unless valid?(:base)

      application_form.update(phone_number: phone_number)
    end

    def save_address(application_form)
      return false unless valid?(:address)

      application_form.update(
        address_line1: address_line1,
        address_line2: address_line2,
        address_line3: address_line3,
        address_line4: address_line4,
        postcode: postcode.upcase,
        country: 'UK',
      )
    end
  end
end

app/models/candidate_interface/course_chosen_form.rb
module CandidateInterface
  class CourseChosenForm
    include ActiveModel::Model

    attr_accessor :choice

    validates :choice, presence: true

    def chosen_a_course?
      choice == 'yes'
    end
  end
end

app/models/candidate_interface/degree_form.rb
module CandidateInterface
  class DegreeForm
    include ActiveModel::Model
    include ValidationUtils

    CLASSES = %w[first upper_second lower_second third].freeze

    attr_accessor :id, :qualification_type, :subject, :institution_name, :grade,
                  :other_grade, :predicted_grade, :award_year

    validates :qualification_type, :subject, :institution_name, presence: true, on: :base
    validates :grade, presence: true, on: :grade
    validates :other_grade, presence: true, if: :other_grade?, on: :grade
    validates :predicted_grade, presence: true, if: :predicted_grade?, on: :grade
    validates :award_year, presence: true, on: :award_year

    validates :qualification_type, :subject, :institution_name, length: { maximum: 255 }, on: :base
    validates :grade, length: { maximum: 255 }, on: :grade
    validates :other_grade, :predicted_grade, length: { maximum: 255 }, on: :grade

    validate :award_year_is_date, if: :award_year, on: :award_year

    class << self
      def build_all_from_application(application_form)
        application_form.application_qualifications.degrees.order(created_at: :desc).map do |degree|
          new_degree_form(degree)
        end
      end

      def build_from_qualification(qualification)
        new_degree_form(qualification)
      end

    private

      def new_degree_form(degree)
        grade = determine_application_grade(degree.grade, degree.predicted_grade)

        new(
          id: degree.id,
          qualification_type: degree.qualification_type,
          subject: degree.subject,
          institution_name: degree.institution_name,
          grade: grade,
          other_grade: grade == 'other' ? degree.grade : '',
          predicted_grade: degree.predicted_grade ? degree.grade : '',
          award_year: degree.award_year,
        )
      end

      def determine_application_grade(grade, predicted_grade)
        case grade
        when *CLASSES
          grade
        else
          if predicted_grade
            'predicted'
          else
            'other'
          end
        end
      end
    end

    def save_base(application_form)
      return false unless valid?(:base)

      application_form.application_qualifications.create!(
        level: ApplicationQualification.levels['degree'],
        qualification_type: qualification_type,
        subject: subject,
        institution_name: institution_name,
      )
    end

    def update_grade(application_form)
      return false unless valid?(:grade)

      degree = application_form.application_qualifications.find(id)

      degree.update!(
        grade: determine_grade,
        predicted_grade: predicted_grade? ? true : false,
      )

      true
    end

    def update_year(application_form)
      return false unless valid?(:award_year)

      degree = application_form.application_qualifications.find(id)

      degree.update!(
        award_year: award_year,
      )

      true
    end

    def update_base(application_form)
      return false unless valid?(:base)

      degree = application_form.application_qualifications.find(id)

      degree.update!(
        qualification_type: qualification_type,
        subject: subject,
        institution_name: institution_name,
      )
    end

    def title
      "#{qualification_type} #{subject}"
    end

  private

    def other_grade?
      grade == 'other'
    end

    def predicted_grade?
      grade == 'predicted'
    end

    def award_year_is_date
      valid_award_year = valid_year?(award_year)
      errors.add(:award_year, :invalid) unless valid_award_year
    end

    def determine_grade
      case grade
      when 'other'
        other_grade
      when 'predicted'
        predicted_grade
      else
        grade
      end
    end
  end
end

app/models/candidate_interface/eligibility_form.rb
module CandidateInterface
  class EligibilityForm
    include ActiveModel::Model

    attr_accessor :eligible_citizen, :eligible_qualifications
    validates :eligible_citizen, :eligible_qualifications, presence: true

    def eligible_to_use_dfe_apply?
      eligible_citizen == 'yes' &&
        eligible_qualifications == 'yes'
    end
  end
end

app/models/candidate_interface/further_information_form.rb
module CandidateInterface
  class FurtherInformationForm
    include ActiveModel::Model

    attr_accessor :further_information, :further_information_details

    validates :further_information, presence: true
    validates :further_information_details, presence: true, if: :further_information?

    validates :further_information_details, word_count: { maximum: 300 }

    def save(application_form)
      return false unless valid?

      application_form.update(
        further_information: further_information? ? further_information_details : '',
      )
    end

    def further_information?
      further_information == 'true'
    end
  end
end

app/models/candidate_interface/pick_provider_form.rb
module CandidateInterface
  class PickProviderForm
    include ActiveModel::Model

    attr_accessor :code
    validates :code, presence: true

    def other?
      Course.exposed_in_find.pluck(:provider_id).exclude?(Provider.find_by(code: code).id)
    end

    def available_providers
      @available_providers ||= begin
        Provider.all.order(:name)
      end
    end
  end
end

app/views/candidate_interface/referees/_form.html.erb
<p class="govuk-body">Contact your referee in advance to check they are:</p>
<ul class="govuk-list govuk-list--bullet">
  <li>happy to give you a reference</li>
  <li>able to submit the reference within a reasonable timeframe</li>
  <li>comfortable submitting a reference online</li>
</ul>

<%= f.govuk_text_field :name, label: { text: t('application_form.referees.name.label'), size: 'm' } %>
<% if HostingEnvironment.sandbox_mode? %>
  <div class="app-status-box app-status-box--sandbox govuk-!-margin-bottom-4">
    <p class="govuk-body">
      <strong class="govuk-tag govuk-phase-banner__content__tag app-environment-tag app-environment-tag--sandbox">
        sandbox feature
      </strong>
    </p>
    <p class="govuk-body govuk-!-margin-bottom-0">
      Enter <code>refbot1@example.com</code> and <code>refbot2@example.com</code> as your referee email addresses to have the references automatically completed
    </p>
  </div>
<% end %>
<%= f.govuk_text_field :email_address, type: 'email', label: { text: t('application_form.referees.email_address.label'), size: 'm' }, hint_text: t('application_form.referees.email_address.hint_text').first %>
<%= f.govuk_text_area :relationship, label: { text: t('application_form.referees.relationship.label'), size: 'm' }, hint_text: t('application_form.referees.relationship.hint_text'), max_words: 50 %>

<%= f.govuk_submit t('application_form.work_history.complete_form_button') %>

app/views/candidate_interface/referees/_intro.html.erb
<p class="govuk-body">We’ll submit your application to your training provider once we receive <%= ApplicationForm::MINIMUM_COMPLETE_REFERENCES %> references for you. Choose referees who’ll endorse your:</p>
<ul class="govuk-list govuk-list--bullet">
  <li>teaching passion and potential</li>
  <li>suitability to work with children</li>
  <li>academic abilities</li>
  <li>reliability and professionalism</li>
</ul>
<p class="govuk-body">Suitable referees include:</p>

<ul class="govuk-list govuk-list--bullet">
  <li>your current line manager at work</li>
  <li>previous employers</li>
  <li>a teacher at a school where you work or volunteer</li>
  <li>your university tutor or supervisor</li>
  <li>a supplier or client you’ve worked with (if you’re self-employed)</li>
</ul>

<p class="govuk-body">Referees should not be family members, partners or friends. Training providers will only accept character references if there’s also an academic or professional reference. </p>
<p class="govuk-body">If you're not sure if your referees are suitable, contact your provider to discuss this.</p>
<div class="govuk-warning-text govuk-!-margin-bottom-4">
  <span class="govuk-warning-text__icon" aria-hidden="true">!</span>
  <strong class="govuk-warning-text__text">
    <span class="govuk-warning-text__assistive">Warning</span>
    We won’t contact your referees until you submit your application
  </strong>
</div>

<p class="govuk-body">If your referees don’t respond, we’ll get back in touch with you to ask for a replacement.</p>

<p class="govuk-body">
  <%= govuk_button_link_to 'Continue', candidate_interface_new_referee_path %>
</p>

app/views/candidate_interface/referees/confirm_destroy.html.erb
<% content_for :title, t('page_titles.referee_destroy') %>
<% content_for :before_content, govuk_back_link_to(candidate_interface_review_referees_path, 'Back') %>

<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <%= form_with model: @referee, url: candidate_interface_destroy_referee_path(@referee.id), method: :delete do |f| %>
      <h1 class="govuk-heading-xl">
        <span class="govuk-caption-xl"><%= @referee.name %></span>
        <%= t('page_titles.referee_destroy') %>
      </h1>

      <%= f.submit t('application_form.referees.sure_delete_entry'), class: 'govuk-button govuk-button--warning', data: { module: 'govuk-button' } %>

      <p class="govuk-body">
        <%= govuk_link_to 'Cancel', candidate_interface_review_referees_path %>
      </p>
    <% end %>
  </div>
</div>

app/views/candidate_interface/referees/edit.html.erb
<% content_for :title, title_with_error_prefix(t('page_titles.add_referee'), @referee.errors.any?) %>
<% content_for :before_content, govuk_back_link_to(candidate_interface_application_form_path, 'Back to application') %>

<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <%= form_with model: @referee, url: candidate_interface_update_referee_path(@referee) do |f| %>
      <%= f.govuk_error_summary %>

      <h1 class="govuk-heading-xl">
        <span class="govuk-caption-xl">
          <%= t('page_titles.nth_referee')[@referee.ordinal] %>
        </span>
        <%= t('page_titles.add_referee') %>
      </h1>

      <%= render 'form', f: f %>
    <% end %>
  </div>
</div>

app/views/candidate_interface/referees/index.html.erb
<% content_for :before_content, govuk_back_link_to(candidate_interface_application_form_path, 'Back to application') %>

<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">

    <% if @referees.empty? %>
      <% content_for :title, t('page_titles.referees_choosing') %>
      <h1 class="govuk-heading-xl">
        <%= t('page_titles.referees_choosing') %>
      </h1>
      <%= render partial: 'intro' %>
    <% else %>
      <%= render(CandidateInterface::RefereesReviewComponent, application_form: @application_form) %>

      <% content_for :title, t('page_titles.referees') %>
      <h1 class="govuk-heading-xl">
        <%= t('page_titles.referees') %>
      </h1>
      <%= govuk_button_link_to t('application_form.referees.review.button'), candidate_interface_application_form_path %>
    <%- end %>

  </div>
</div>

app/views/candidate_interface/referees/new.html.erb
<% content_for :title, title_with_error_prefix(t('page_titles.add_referee'), @referee.errors.any?) %>
<% content_for :before_content, govuk_back_link_to(candidate_interface_application_form_path, 'Back to application') %>

<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <%= form_with model: @referee, url: candidate_interface_referees_path do |f| %>
      <%= f.govuk_error_summary %>

      <h1 class="govuk-heading-xl">
        <span class="govuk-caption-xl">
          <%= t('page_titles.nth_referee')[@referee.ordinal] %>
        </span>
        <%= t('page_titles.add_referee') %>
      </h1>

      <%= render 'form', f: f %>
    <% end %>
  </div>
</div>

app/views/candidate_interface/referees/review.html.erb
<% content_for :title, t('page_titles.referees') %>
<% content_for :before_content, govuk_back_link_to(candidate_interface_application_form_path, 'Back to application') %>

<h1 class="govuk-heading-xl">
  <%= t('page_titles.referees') %>
</h1>

<% editable = @application_form.amendable? ? false : true %>
<%= render(CandidateInterface::RefereesReviewComponent, application_form: @application_form, editable: editable) %>

<%- if @referees.count < ApplicationForm::MINIMUM_COMPLETE_REFERENCES %>
<p>
  <% if @referees.any? %>
    <%= govuk_button_link_to t('application_form.referees.add_second_referee'), candidate_interface_new_referee_path, class: 'govuk-button--secondary' %>
  <% else %>
    <%= govuk_button_link_to t('application_form.referees.add_referee'), candidate_interface_new_referee_path, class: 'govuk-button--secondary' %>
  <% end %>
</p>
<%- end %>

<p>
  <%= govuk_button_link_to t('application_form.referees.review.button'), candidate_interface_application_form_path %>
</p>